### ISSUE TITLE
How can I make a swipe transition? 

### ISSUE THREAD

**Issue by davidmarinangeli** [dev-labs-bg/transitioner#3]
Hello! 

I really like your library and I'm trying to develop a transition like the weather app on your Readme: how could I make an up/down swipe? 

I've tried with this but the result is VERY BAD.  Do you know where I can find some examples? Thanks. 
`var screenSize = size.y
        screen.setOnTouchListener { v, event ->
            when (event.action) {
                MotionEvent.ACTION_DOWN -> {
                    oldY = event.y
                    true
                }
                MotionEvent.ACTION_MOVE -> {
                    transition.setProgress((event.y - oldY)/screenSize)
                    true
                }
                else -> {
                    true
                }
            }
        }`

**Comment by radoyankov** [comment]
Which part exactly looks bad? If you are trying to set the touch listener on the element you are resizing ("screen") you will get a weird twitch on the view. If this is your problem, try setting the touch listener on another view, one which is static (I usually set it on the root one).

**Comment by davidmarinangeli** [comment]
screen is the static/root one (the constraintlayout). The result is the disaster you can see down below. : \

https://photos.app.goo.gl/VTdkIDg4JR1itcqe2

**Comment by davidmarinangeli** [comment]
XML:
https://gist.github.com/davidmarinangeli/075b489ac91703c88a149a3d0e8d4787
Kotlin:
https://gist.github.com/davidmarinangeli/aa8657525fe2f43d215045932bb6226c

**Comment by radoyankov** [comment]
Before you create your Transitioner object you have to wait for the screen and the views to be drawn. I recommend placing it in a layout listener or, like the example shows, to add a small delay before creating the object.

**Comment by davidmarinangeli** [comment]
Ok I create a layout listener and it works, but the animation in REALLY fast, I hope to adjust it by my own. Thanks a lot!
