### ISSUE TITLE
AnimateTo Bug?

### ISSUE THREAD

**Issue by davidmarinangeli** [dev-labs-bg/transitioner#4]
Hello, I'm still trying to do some animations with transitioner: unfortunately, I'm experiencing a lot of issues. 

For example, in code I linked below I can expand my cardview with a "scroll down gesture" but I can't reduce it with a swipe up (I debugged the code and the if clauses are correctly called):

https://gist.github.com/davidmarinangeli/7eec8455654850b3d3540ff9a9384bd6

You can find the XML here: https://gist.github.com/davidmarinangeli/a4d0724d0f0283096e81e7ecf357c788

**Comment by radoyankov** [comment]
From what I'm seeing, I don't see anything wrong with the way you are using the library. I've tested it multiple times, in similar environments and it's been working fine. Maybe try a different approach, try changing some variables or debug it a little bit more, I can't really more than that based on what I know of your app.

**Comment by davidmarinangeli** [comment]
Uhm, I'm able to expand the card with a swipe down but not "reduce" it with a swipe up and...it should (the animateTo method should do this, shoudn't it?)

**Comment by radoyankov** [comment]
Yes, the code is pretty straight forward, it's just a value animator from the current progress (which in your case shsould be 1f) to the desired one (0f) and a call to setProgress() on each update with the value of the animation so I don't think that can be a problem.
```
ValueAnimator.ofFloat(currentProgress, endProgress).apply{
            addUpdateListener { animation ->
                setProgress(animation.animatedValue as Float)
            }
            start()
}
```

**Comment by davidmarinangeli** [comment]
Is the XML correct for the correct usage of the library? I mean tags and hiearchy of the views...

**Comment by davidmarinangeli** [comment]
Maybe the only thing that I need is some samples of code developed by you or some expert developer of the library.

Sorry for the inconvenience.

**Comment by radoyankov** [comment]
Alright, two things.
-First, I should have probably written this down somewhere, but in order for the library to work, you have to wait for all participating views to load before you initialize your Transitioner object. So I would place the creation of the object somewhere where I am certain the views would have loaded already (or, as I like to do it, wait for 1-2sec, **then** create the Transitioner object).

-Second, I recreated your program, xml and all, and this is the outcome when I put the animation in a loop:

![gif](https://user-images.githubusercontent.com/17084989/38267562-95747d14-3784-11e8-8cdb-d854d540f6cb.gif)

**Comment by davidmarinangeli** [comment]
I really appreciate your help! Thanks!!

However, now I see that the problem is mine: can you share the code? 

I checked mine and I create all the views after this call
```
val rootView = window.decorView.rootView
        rootView.viewTreeObserver.addOnGlobalLayoutListener {
            //by now all views will be displayed with correct values
            addAnimationOperations() <- this function create all the listeners

        }
```

**Comment by davidmarinangeli** [comment]
However, I wrote a delay of 2000ms as you did in the sample app and now works...
