### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;

### ISSUE THREAD

**Issue by krunalindrodiya** [dev-labs-bg/transitioner#5]
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/**/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

**Comment by radoyankov** [comment]
Are you using the kotlin stdlib-jre7? Because it doesn't work on Android, which supports only Java 6. When targeting Android, you should use kotlin stdlib, which is built for 6:
`compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"`

**Comment by krunalindrodiya** [comment]
I am not using kotlin, i am use this library in java android application.

**Comment by radoyankov** [comment]
This is a Kotlin only library. You must have the language configured in your project in order to use it.
